title: Matthew Beasley
logo: assets/img/Round_Headshot.png
description: Hello! Im Matthew Beasley, a dedicated Mechanical Engineering student emphasizing in design and manufacturing at the University of Utah. Committed to fostering a well-rounded academic experience while building valuable connections for the future. Previously serving as the academic advisor for Sigma Phi Epsilon fraternity, overseeing 160+ active members. Actively involved in The National Honors Society, ASME, University of Utah Cycling Club, and University of Utah Bowling Club. 
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
